%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\SIM202\Projet\Test.txt
%
% Auto-generated by MATLAB on 01-Feb-2022 10:02:36

%% Setup the Import Options and import the data
clear all
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["i", "x", "y"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
tbl = readtable("C:\SIM202\Projet\Sommet.txt", opts);

%% Convert to output type
Coorneu=cat(2,tbl.x,tbl.y);

%% Clear temporary variables
clear opts tbl

%%%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["i", "Sommet1", "Sommet2", "Sommet3"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
tbl = readtable("C:\SIM202\Projet\Triangle.txt", opts);

%% Convert to output type
Numtri=cat(2,tbl.Sommet1+1,tbl.Sommet2+1,tbl.Sommet3+1);

%% Clear temporary variables
clear opts tbl